title: Cleveland Office Movers
email: bryan@clevelandofficemovers.com
description: >- 
  Cleveland Office Movers - Providing quality office relocation services to our clients using professionally trained office movers
meta-tags: [Cleveland, moving, movers, office movers, relocation, office moving, Bryan Berry]

baseurl: "" 
url: "https://clevelandofficemovers.com" 

markdown: kramdown
safe: false

plugins:
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - node_modules/
